// Generated by npm run generate:validator. Do not edit.
export declare function validateRecord(value: unknown): boolean;
export declare function validateIndex(value: unknown): boolean;
export declare function validateDetail(value: unknown): boolean;
